    
    zn "USER" 
    
    zpm "install isc-dev" 
    do ##class(dev.code).workdir("/home/irisowner/irisdev/src") 
    do EnableDeepSee^%SYS.cspServer("/csp/user/") 

    zpm "load /home/irisowner/irisdev/ -v"

    zn "%SYS" 
    Do ##class(Security.Users).UnExpireUserPasswords("*")
    write "Modifying MDX2JSON application security...",! 
    set webName = "/mdx2json" 
    set webProperties("AutheEnabled") = 64 
    set webProperties("MatchRoles")=":%DB_USER" 
    set sc = ##class(Security.Applications).Modify(webName, .webProperties) 
    if sc<1 write $SYSTEM.OBJ.DisplayError(sc) 

    halt
