zn "%SYS" 
Do ##class(Security.Users).UnExpireUserPasswords("*")
do $SYSTEM.OBJ.Load("/opt/irisapp/Installer.cls", "ck")
set sc = ##class(App.Installer).setup() 
zn "IRISAPP" 
zpm "install sslclient" 
zpm "install csvgen"
do ##class(Covid19.Utils).ImportData() 
do ##class(Covid19.Utils).BISetup() 
do ##class(Covid19.Utils).CreateTask() 
do ##class(User.Utils).Setup()
zpm "install dsw" 
zpm "install isc-dev" 
do ##class(dev.code).workdir("/irisdev/app/src") 
do EnableDeepSee^%SYS.cspServer("/csp/irisapp/") 
do ##class(Covid19.Utils).OpenToPublic()
halt
