Class User.CT.EventType Extends (%Persistent, CodeDescAbstract)
{

Storage Default
{
<Data name="EventTypeDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Active</Value>
</Value>
<Value name="3">
<Value>Code</Value>
</Value>
<Value name="4">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^User.CT.EventTypeD</DataLocation>
<DefaultData>EventTypeDefaultData</DefaultData>
<IdLocation>^User.CT.EventTypeD</IdLocation>
<IndexLocation>^User.CT.EventTypeI</IndexLocation>
<StreamLocation>^User.CT.EventTypeS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
